name: interviewhatak
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # Flutter Widgets that Built to be used with the bloc state management package.
  flutter_bloc: ^8.1.6
  # Simple direct Service Locator that allows to decouple the interface from a concrete implementation and to access the concrete implementation from everywhere in your App"
  get_it: ^8.0.2
  # Code generation for immutable classes that has a simple syntax/API without compromising on the features.
  freezed: ^2.5.7
  # Annotations for the freezed code-generator. This package does nothing without freezed too.
  freezed_annotation: ^2.4.4
  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.4.13
  # A Flutter package to use fonts from fonts.google.com.
  google_fonts: ^6.2.1
  # A flutter plugin for adapting screen and font size.Guaranteed to look good on different data
  flutter_screenutil: ^5.9.3
  # A package which simplifies the task of updating your Flutter app's launcher icon.
  flutter_launcher_icons: ^0.14.2
  # Customizable animated page indicator with a set of built-in effects.
  smooth_page_indicator: ^1.2.0+3
  # Flutter plugin for Firebase Core, enabling connecting to multiple Firebase apps.
  firebase_core: ^3.8.1
  # Flutter plugin for Firebase Auth, enabling authentication using passwords, phone numbers and identity providers like Google, Facebook and Twitter.
  firebase_auth: ^5.3.4
  # Flutter plugin for Cloud Firestore, a cloud-hosted, noSQL database with live synchronization and offline support on Android and iOS.
  cloud_firestore: ^5.5.1

  icon_broken: ^1.1.0
  # A collection of loading indicators animated with flutter.
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path_android: "assets/images/logo.png"
  image_path_ios: "assets/images/logo.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/images/background.png"
  adaptive_icon_foreground: "assets/images/logo.png"


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/