// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKRx0v2STxvpuYztmxhhu1LyGdR_tlYWk',
    appId: '1:587240536640:web:8036a8983a4b483380fda5',
    messagingSenderId: '587240536640',
    projectId: 'interview-hatk',
    authDomain: 'interview-hatk.firebaseapp.com',
    storageBucket: 'interview-hatk.firebasestorage.app',
    measurementId: 'G-4PM0JFVJWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkt9yfezMCrqFuXYnjHV_J-WZh3LPw8l0',
    appId: '1:587240536640:android:6d99eb419c096d8b80fda5',
    messagingSenderId: '587240536640',
    projectId: 'interview-hatk',
    storageBucket: 'interview-hatk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP6QOmPRiHGEGEsJvq-3iH0X8YFjHV328',
    appId: '1:587240536640:ios:53476f7e715c42a680fda5',
    messagingSenderId: '587240536640',
    projectId: 'interview-hatk',
    storageBucket: 'interview-hatk.firebasestorage.app',
    iosBundleId: 'com.preparation.interviewhatak.interviewhatak',
  );

}